### ISSUE TITLE
Make -x option raise the actual exception

### ISSUE THREAD

**Issue by stestagg** [hyde/hyde#305] opened 2015-12-19 13:47 UTC
I've been writing some more complex plugins for hyde, and struggling with debugging, because the -x option doesn't actually raise the original exception.

For example:
```
 13:43:50 hyde Error occured when calling indexer
Traceback (most recent call last):
  File "/usr/bin/hyde", line 9, in <module>
    load_entry_point('hyde==0.8.9', 'console_scripts', 'hyde')()
  File "/usr/lib/python2.7/site-packages/hyde/main.py", line 11, in main
    Engine().run()
  File "/usr/lib/python2.7/site-packages/commando/application.py", line 309, in run
    args.run(self, args)
  File "/usr/lib/python2.7/site-packages/hyde/engine.py", line 102, in gen
    gen.generate_all(incremental=incremental)
  File "/usr/lib/python2.7/site-packages/hyde/generator.py", line 216, in generate_all
    self.__generate_node__(self.site.content, incremental)
  File "/usr/lib/python2.7/site-packages/hyde/generator.py", line 313, in __generate_node__
    self.__generate_resource__(resource, incremental)
  File "/usr/lib/python2.7/site-packages/hyde/generator.py", line 350, in __generate_resource__
    resource, text) or text
  File "/usr/lib/python2.7/site-packages/hyde/plugin.py", line 95, in __call_plugins__
    plugin.plugin_name, sys.exc_info())
  File "/usr/lib/python2.7/site-packages/hyde/plugin.py", line 91, in __call_plugins__
    res = function(*args)
  File "/home/sstagg/src/pythonjobs/template/hyde/siteindex.py", line 98, in text_resource_complete
    self.write_text_resource(resource.slug, parts)
  File "/home/sstagg/src/pythonjobs/template/hyde/siteindex.py", line 106, in write_text_resource
    self.deploy(content, "excerpts/%s.txt" % (name, ))
  File "/home/sstagg/src/pythonjobs/template/hyde/siteindex.py", line 114, in deploy
    fh.write(content)
hyde.exceptions.HydeException: Error occured when calling indexer
```

Is missing the critical piece of information here:

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 14: ordinal not in range(128)
```

**Comment by lakshmivyas** [comment] 2015-12-20 12:43
I thought this issue had been fixed a while back.  Thanks @stestagg.  Will take a look.

**Comment by jonafato** [comment] 2016-03-01 04:28
With current master, hyde seems to behave correctly and usefully here. Although it does not raise the original exception (instead it wraps it with `HydeException`), it contains all the info needed to diagnose the issues.

For example, with a new site created by `hyde create`, if I add `{{ 1 / 0 }}` to my `content/index.html` and run `hyde -x gen`, it outputs a lot of information and finally includes a useful exception info line at the end:

```
hyde.exceptions.HydeException: Error occurred when processingtemplate: [/Users/jonafato/.virtualenvs/tmp-ee0189f2335d78a/content/index.html]: ZeroDivisionError('division by zero',)
```

@stestagg Do you still see this behavior with master or recent releases of Hyde? If so, can you provide a minimal example that causes the issue?

**Comment by jonafato** [comment] 2016-05-13 19:28
This appears to be fixed in `master`, so I'm going to close this issue. If it can be reproduced using the code on the `master` branch, feel free to reopen.

**Closed by jonafato** 2016-05-13 19:28 UTC
